### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by jakeledoux** [jakeledoux/crabber#10]
Why a REST API?
----
One thing about the internet that makes it so awesome is the ability to strap together so many different services and create interesting combinations of them. People's creativity is amazing and it's cool seeing all the fun things they come up with. 

Twitter has always had cool novelty bot accounts that would do really interesting things, but unfortunately their API has become more and more locked down as they grow. This makes sense, they have an ethical responsibility to restrict misuse of their service to promote misinformation and discord. However, we don't yet have to worry about that, and a REST API would be a tremendously fun thing to have.

In addition to its uses with novelty/bot accounts, it would also allow people to develop their own third-party clients for the website. This would allow native mobile applications, command line interfaces, and a number of other interesting adaptations of the Crabber service.

Requirements for a proper implementation
----
* **Good documentation.** It should be simple and easy for a developer to start using this API.
* **Well structured methods.** In addition to documentation, using the API should be intuitive and comfortable.
* **Good coverage.** In order for things like 3rd-party clients to be developed, everything that can be done on the website should be accessible via the API.
* **Secure implementation.** OAuth2 should be supported for easy user-side authentication, but we should also support authentication via hashed passwords in order to support headless programs.
* **API keys.** It should be easy but required for devs to register their app before use, so that we can shut down malicious or rule-breaking applications quickly.
* **Rate limit/caching.** Preventing unnecessary server load should be a top priority, especially for artificial traffic, as web users remain our number one concern. Results should be cached, and applications should be restricted to X amount of requests per sec/min.

This is just an outline of what I imagine for Crabber's API implementation, much discussion will still need to be done throughout development of this feature.

**Comment by Brennakm** [comment]
Hi, I'm not a developer but I am happy to write API documentation when the times comes. Thanks!

**Comment by jakeledoux** [comment]
Finally, work has begun on the API! I've figured out how I'll structure the Flask routing and database access. I've seen lots of cool modules for creating APIs but for the scope and structure of this project I think Flask Blueprints make the most sense. Now it's just a matter of:

- Working out the necessary endpoints
- Choosing data structures
- Implementing the endpoints (of which I've already started a few)

and then once that's complete we'll need an authentication flow for developers. All this is available on [the "rest-api" branch](https://github.com/jakeledoux/crabber/tree/rest-api).

Then maybe once this is all said and done I can write a Python module. We'll cross that bridge when we get there.

**Comment by jakeledoux** [comment]
Initial documentation can be found [here](https://app.swaggerhub.com/apis-docs/jakeledoux/Crabber/1.0.0).

**Comment by jakeledoux** [comment]
@Brennakm If you're still interested, proper documentation would be a great help to the project! I've linked a barebones layout above and any additional information can be found in the files [crabber_api.py](https://github.com/jakeledoux/crabber/blob/master/crabber_api.py) and [api_utils.py](https://github.com/jakeledoux/crabber/blob/master/api_utils.py).

**Comment by greysdawn** [comment]
hi! sorry to open this again, i figured it'd be better than opening a new issue

i decided to have some fun and write up an api wrapper for js, but i noticed that some of the documentation (specifically the section about fetching molts) is incorrect. i came back here to see if i can fix it for ya, but i'm not actually sure what i need to edit (if i even *can* edit things here) to make that happen- i'm not super familiar with swaggerhub personally, and the `rest-api` branch doesn't seem to exist anymore 😅

what can i do to help out?

**Comment by jakeledoux** [comment]
I'd appreciate that! Writing docs is one of those things that I always mean to do but never really have the time for. Thanks :)
